#!/usr/bin/python3

import sys, getopt
import csv
import json
import pandas as pd
import numpy as np
from pprint import pprint
import requests as req

#Entity Framework for OAuth
#important import: curl -OL https://github.com/requests/requests/tarball/master
#Get Command Line Arguments
#format on CLI: python csv-json.py -i users.csv -o users.json -f dump
url='http://mlangston.xyz/api/MedicalController'
def main(argv):
    #don't forget to change path in CLI, but these are default paths
    sample1 = '/Users/RachelDedinsky/Desktop/senior/capstone 1/project/SPElderCare/medical_backend/log.csv'
    sample2 = '/Users/RachelDedinsky/Desktop/senior/capstone 1/project/SPElderCare/medical_backend/log1.csv'
    input_file = '/Users/RachelDedinsky/Desktop/senior/capstone 1/project/SPElderCare/medical_backend/log2.csv'
    output_file = '/Users/RachelDedinsky/Desktop/senior/capstone 1/project/SPElderCare/medical_backend/json.json'
    format = ''
    #Command line arguments set the file paths
    try:
        opts, args = getopt.getopt(argv,"hi:o:f:",["ifile=","ofile=","format="])
    except getopt.GetoptError:
        print ('csv_json.py -i <path to inputfile> -o <path to outputfile> -f <dump/pretty>')
        sys.exit(2)
    for opt, arg in opts:
        if opt == '-h':
            print ('csvtojson.py -i <path to inputfile> -o <path to outputfile> -f <dump/pretty>')
            sys.exit()
        elif opt in ("-i", "--ifile"):
            input_file = arg
        elif opt in ("-o", "--ofile"):
            output_file = arg
        elif opt in ("-f", "--format"):
            format = arg

    #get rid of the date header which is autogenerated by protocentral HAT GUI
    with open(sample1,'r+') as f:
        with open(sample2,'w+') as f1:
            f.readline() # skip header line
            f1.write((f.readline())[11:])
            for line in f:
                line = line[9:]
                f1.write(line)

    #set up pandas to read dataframes and check whether or not each data field exists in the file. if not,
    #create with a default value of 0. Note, this stores the averages of the input file. This version of
    #the file is stored on the server.
    df = pd.read_csv(sample2)
    userID=1
    health=bool(1)
    if 'ECG' in df:
        df1=df['ECG'].mean()
    else:
        df1=0
    if 'SpO2' in df:
        df2=df['SpO2'].mean()
    else:
        df2=p0
    if 'Respiration' in df:
        df3=df['Respiration'].mean()
    else:
        df3=0
    if 'Pulse' in df:
        df4=df['Pulse'].mean()
    else:
        df4=0
    if 'BloodPressure' in df:
        df5=df['BloodPressure'].mean()
    else:
        df5=0

    if df1!=0 and (df1>100 or df1<60):
        health=bool(0)
    elif df2!=0 and (df2<94):#if less that 94 percent
        health=bool(0)
    elif df3!=0 and (df3<12 or df3>25):
        health=bool(0)
    elif df4!=0 and (df4<40 and df4>100):
        health=bool(0)
    elif df5!=0 and (df5<1):
        health=bool(0)
    else:
        health=bool(1)

    series=[userID,df1,df2,df3,df4,df5,health]
    header=["UserID","ECG","SpO2","Respiration","Pulse","BloodPressure","health"]

    #write the averaged format to the input file
    with open(input_file,'w+') as f1:
        writer = csv.writer(f1)
        writer.writerows([header])
        writer.writerows([series])
    read_csv(input_file, output_file, format)
    data = json.load(open(output_file))
    pprint(data)
    headers = {'Content-type': 'multipart/json'}
    resp = req.post(url, json=data, headers=headers)
	#print (r.text)

#Read CSV File
def read_csv(file, json_file, format):
    csv_rows = []
    with open(file) as csvfile:
        reader = csv.DictReader(csvfile)
        title = reader.fieldnames
        for row in reader:
            csv_rows.extend([{title[i]:row[title[i]] for i in range(len(title))}])
        write_json(csv_rows, json_file, format)

#Convert csv data into json and write it
def write_json(data, json_file, format):
    with open(json_file, "w") as f:
        if format == "pretty":
            f.write(json.dumps(data, sort_keys=False, indent=4, separators=(',', ': '),encoding="utf-8",ensure_ascii=False))
        else:
            f.write(json.dumps(data))

if __name__ == "__main__":
   main(sys.argv[1:])
