// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SPECS_Web_Server.Data;
using System;

namespace SPECS_Web_Server.Migrations
{
    [DbContext(typeof(SPECSDbContext))]
    partial class SPECSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("SPECS_Web_Server.Models.AlexaSession", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessToken");

                    b.Property<string>("ApiAccessToken");

                    b.Property<string>("ApiEndpoint");

                    b.Property<string>("ApplicationUserId");

                    b.Property<string>("DeviceID");

                    b.Property<string>("Locale");

                    b.Property<string>("RequestId");

                    b.Property<DateTime>("Timestamp");

                    b.Property<string>("Type");

                    b.Property<string>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("AlexaSessions");
                });

            modelBuilder.Entity("SPECS_Web_Server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("Address1");

                    b.Property<string>("Address2");

                    b.Property<string>("AlexaID");

                    b.Property<string>("City");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Country");

                    b.Property<int?>("DevicePermissionID");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.Property<int?>("familyID");

                    b.HasKey("Id");

                    b.HasIndex("DevicePermissionID");

                    b.HasIndex("familyID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("SPECS_Web_Server.Models.DevicePermission", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeviceID");

                    b.Property<int?>("FamilyID");

                    b.Property<bool>("access");

                    b.Property<string>("deviceInfo");

                    b.Property<string>("deviceOwnerId");

                    b.HasKey("ID");

                    b.HasIndex("FamilyID");

                    b.HasIndex("deviceOwnerId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("SPECS_Web_Server.Models.Family", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("ID");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("SPECS_Web_Server.Models.MedicalSensorData", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicationUserId");

                    b.Property<string>("BloodPressure");

                    b.Property<float>("ECG");

                    b.Property<int>("Pulse");

                    b.Property<float>("SpO2");

                    b.Property<bool>("healthy");

                    b.HasKey("ID");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("MedicalData");
                });

            modelBuilder.Entity("SPECS_Web_Server.Models.AlexaSession", b =>
                {
                    b.HasOne("SPECS_Web_Server.Models.ApplicationUser")
                        .WithMany("alexaSessionData")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("SPECS_Web_Server.Models.ApplicationUser", b =>
                {
                    b.HasOne("SPECS_Web_Server.Models.DevicePermission")
                        .WithMany("grantedTo")
                        .HasForeignKey("DevicePermissionID");

                    b.HasOne("SPECS_Web_Server.Models.Family", "family")
                        .WithMany("members")
                        .HasForeignKey("familyID");
                });

            modelBuilder.Entity("SPECS_Web_Server.Models.DevicePermission", b =>
                {
                    b.HasOne("SPECS_Web_Server.Models.Family")
                        .WithMany("devicePermissions")
                        .HasForeignKey("FamilyID");

                    b.HasOne("SPECS_Web_Server.Models.ApplicationUser", "deviceOwner")
                        .WithMany()
                        .HasForeignKey("deviceOwnerId");
                });

            modelBuilder.Entity("SPECS_Web_Server.Models.MedicalSensorData", b =>
                {
                    b.HasOne("SPECS_Web_Server.Models.ApplicationUser")
                        .WithMany("MedicalSensorData")
                        .HasForeignKey("ApplicationUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
